"""Magnet Rush — shared Blender authoring kit.

Every runtime asset in this game is generated by script, headlessly, so the
art pipeline is reproducible and reviewable in version control rather than
living inside binary .blend files.

Run through Blender, never through a bare Python interpreter:

    blender --background --python art/blender/build_assets.py

Conventions enforced here (see docs/blender_pipeline.md):

  * metric scale, 1 Blender unit = 1 metre
  * +Y up, -Z forward at export (glTF convention; the exporter converts)
  * transforms applied, origin at the logical pivot
  * flat shading — the art bible calls for faceted, crystalline geometry
  * a small set of shared materials, so draw calls stay low
"""

from __future__ import annotations

import json
import math
import os
import random

import bmesh
import bpy
from mathutils import Matrix, Vector

# ---------------------------------------------------------------------------
# Palette — the art bible's colour roles, in linear sRGB
# ---------------------------------------------------------------------------

CYAN = (0.05, 0.78, 1.00)
CORE_BLUE = (0.04, 0.30, 0.92)
CORE_DEEP = (0.01, 0.08, 0.38)
ICE = (0.62, 0.92, 1.00)
SILVER = (0.70, 0.76, 0.85)
STEEL = (0.38, 0.43, 0.52)
CHARCOAL = (0.11, 0.13, 0.18)
NAVY = (0.03, 0.05, 0.11)
ORANGE = (1.00, 0.42, 0.10)
AMBER = (1.00, 0.66, 0.22)
GREEN = (0.25, 1.00, 0.52)
RED = (1.00, 0.20, 0.22)
WHITE = (1.00, 1.00, 1.00)

# Triangle budgets from the brief, keyed by asset class.
BUDGETS = {
    "swarm": 500,
    "debris": 300,
    "prop": 2500,
    "interactive": 5000,
    "machine": 10000,
    "boss": 20000,
}


# ---------------------------------------------------------------------------
# Scene lifecycle
# ---------------------------------------------------------------------------


def reset_scene() -> None:
    """Wipes the file back to an empty metric scene."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    # Reloading the file invalidates every cached datablock, so the material
    # cache must go with it or lookups hit a dead StructRNA.
    _material_cache.clear()
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0


def _link(obj: bpy.types.Object) -> None:
    bpy.context.collection.objects.link(obj)


# ---------------------------------------------------------------------------
# Materials
# ---------------------------------------------------------------------------

_material_cache: dict[str, bpy.types.Material] = {}


def material(
    name: str,
    color=SILVER,
    *,
    metallic: float = 0.9,
    roughness: float = 0.35,
    emission=None,
    emission_strength: float = 0.0,
    alpha: float = 1.0,
) -> bpy.types.Material:
    """A Principled BSDF material. Cached, so assets share materials."""
    key = f"{name}"
    hit = _material_cache.get(key)
    if hit is not None:
        try:
            if hit.name in bpy.data.materials:
                return hit
        except ReferenceError:
            # Datablock was freed underneath us; fall through and rebuild.
            _material_cache.pop(key, None)

    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*color, 1.0)
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    if alpha < 1.0:
        bsdf.inputs["Alpha"].default_value = alpha
        mat.blend_method = "BLEND"
    if emission is not None:
        bsdf.inputs["Emission Color"].default_value = (*emission, 1.0)
        bsdf.inputs["Emission Strength"].default_value = emission_strength
    _material_cache[key] = mat
    return mat


def assign(obj: bpy.types.Object, mat: bpy.types.Material) -> bpy.types.Object:
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    return obj


# ---------------------------------------------------------------------------
# Mesh construction
# ---------------------------------------------------------------------------


def from_bmesh(bm: bmesh.types.BMesh, name: str) -> bpy.types.Object:
    mesh = bpy.data.meshes.new(name)
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    _link(obj)
    return obj


def new_bmesh() -> bmesh.types.BMesh:
    return bmesh.new()


def flat_shade(obj: bpy.types.Object) -> bpy.types.Object:
    """Faceted look. The art bible is explicit about this."""
    for poly in obj.data.polygons:
        poly.use_smooth = False
    return obj


def smooth_shade(obj: bpy.types.Object) -> bpy.types.Object:
    for poly in obj.data.polygons:
        poly.use_smooth = True
    return obj


def recalc_normals(obj: bpy.types.Object) -> bpy.types.Object:
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bm.to_mesh(obj.data)
    bm.free()
    obj.data.update()
    return obj


def apply_transforms(obj: bpy.types.Object) -> bpy.types.Object:
    """Bakes loc/rot/scale into the mesh so the runtime gets clean data."""
    obj.data.transform(obj.matrix_world)
    obj.matrix_world = Matrix.Identity(4)
    return obj


def join(objs: list[bpy.types.Object], name: str) -> bpy.types.Object:
    """Merges objects into one mesh, preserving per-face materials."""
    assert objs, "join() needs at least one object"
    target = bpy.data.meshes.new(name)
    bm = bmesh.new()
    mat_index: dict[str, int] = {}
    materials: list[bpy.types.Material] = []

    for obj in objs:
        apply_transforms(obj)
        for slot in obj.data.materials:
            if slot is not None and slot.name not in mat_index:
                mat_index[slot.name] = len(materials)
                materials.append(slot)

    for obj in objs:
        tmp = bmesh.new()
        tmp.from_mesh(obj.data)
        remap = {}
        for i, slot in enumerate(obj.data.materials):
            remap[i] = mat_index.get(slot.name, 0) if slot else 0
        for face in tmp.faces:
            face.material_index = remap.get(face.material_index, 0)
        merged = bpy.data.meshes.new(f"__tmp_{obj.name}")
        tmp.to_mesh(merged)
        tmp.free()
        bm.from_mesh(merged)
        bpy.data.meshes.remove(merged)

    bm.to_mesh(target)
    bm.free()

    out = bpy.data.objects.new(name, target)
    for mat in materials:
        out.data.materials.append(mat)
    _link(out)

    for obj in objs:
        bpy.data.objects.remove(obj, do_unlink=True)
    return out


# ---------------------------------------------------------------------------
# Primitive builders (low-poly by construction)
# ---------------------------------------------------------------------------


def box(name, sx=1.0, sy=1.0, sz=1.0, at=(0, 0, 0), mat=None) -> bpy.types.Object:
    bm = new_bmesh()
    bmesh.ops.create_cube(bm, size=1.0)
    bmesh.ops.scale(bm, vec=Vector((sx, sy, sz)), verts=bm.verts)
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def icosphere(name, radius=1.0, subdiv=1, at=(0, 0, 0), mat=None):
    bm = new_bmesh()
    bmesh.ops.create_icosphere(bm, subdivisions=subdiv, radius=radius)
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def cylinder(name, radius=0.5, depth=1.0, segments=10, at=(0, 0, 0), mat=None,
             cap=True):
    bm = new_bmesh()
    bmesh.ops.create_cone(
        bm,
        cap_ends=cap,
        cap_tris=False,
        segments=segments,
        radius1=radius,
        radius2=radius,
        depth=depth,
    )
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def cone(name, radius=0.5, depth=1.0, segments=8, at=(0, 0, 0), mat=None):
    bm = new_bmesh()
    bmesh.ops.create_cone(
        bm, cap_ends=True, cap_tris=False, segments=segments,
        radius1=radius, radius2=0.0, depth=depth,
    )
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def torus(name, major=1.0, minor=0.15, major_seg=16, minor_seg=6, at=(0, 0, 0),
          mat=None):
    """A low-poly ring — used for the Core's magnetic rings."""
    bm = new_bmesh()
    for i in range(major_seg):
        a = (i / major_seg) * math.tau
        center = Vector((math.cos(a) * major, math.sin(a) * major, 0.0))
        radial = Vector((math.cos(a), math.sin(a), 0.0))
        ring = []
        for j in range(minor_seg):
            b = (j / minor_seg) * math.tau
            offset = radial * (math.cos(b) * minor) + Vector(
                (0, 0, math.sin(b) * minor)
            )
            ring.append(bm.verts.new(center + offset))
        bm.verts.ensure_lookup_table()
    bm.verts.ensure_lookup_table()
    verts = bm.verts[:]
    for i in range(major_seg):
        for j in range(minor_seg):
            a0 = verts[i * minor_seg + j]
            a1 = verts[i * minor_seg + (j + 1) % minor_seg]
            b0 = verts[((i + 1) % major_seg) * minor_seg + j]
            b1 = verts[((i + 1) % major_seg) * minor_seg + (j + 1) % minor_seg]
            bm.faces.new((a0, a1, b1, b0))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def gear(name, teeth=10, inner=0.28, root=0.42, tip=0.58, thickness=0.14,
         at=(0, 0, 0), mat=None):
    """A chunky low-poly gear. Reads clearly at swarm scale."""
    bm = new_bmesh()
    half = thickness * 0.5
    rings_bottom, rings_top = [], []
    step = math.tau / (teeth * 2)
    for i in range(teeth * 2):
        a = i * step
        r = tip if (i % 2 == 0) else root
        rings_bottom.append(bm.verts.new((math.cos(a) * r, math.sin(a) * r, -half)))
        rings_top.append(bm.verts.new((math.cos(a) * r, math.sin(a) * r, half)))
    hub_bottom, hub_top = [], []
    for i in range(teeth * 2):
        a = i * step
        hub_bottom.append(
            bm.verts.new((math.cos(a) * inner, math.sin(a) * inner, -half))
        )
        hub_top.append(bm.verts.new((math.cos(a) * inner, math.sin(a) * inner, half)))

    n = teeth * 2
    for i in range(n):
        j = (i + 1) % n
        bm.faces.new((rings_bottom[i], rings_bottom[j], rings_top[j], rings_top[i]))
        bm.faces.new((hub_top[i], hub_top[j], hub_bottom[j], hub_bottom[i]))
        bm.faces.new((hub_top[i], rings_top[i], rings_top[j], hub_top[j]))
        bm.faces.new((rings_bottom[i], hub_bottom[i], hub_bottom[j], rings_bottom[j]))

    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def crystal(name, radius=1.0, subdiv=1, jitter=0.22, seed=1, at=(0, 0, 0),
            mat=None):
    """A faceted energy crystal: an icosphere pushed off-sphere per vertex.

    This is the Kanban Core silhouette — angular, asymmetrical but balanced.
    """
    rng = random.Random(seed)
    bm = new_bmesh()
    bmesh.ops.create_icosphere(bm, subdivisions=subdiv, radius=radius)
    for v in bm.verts:
        v.co *= 1.0 + rng.uniform(-jitter, jitter)
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


def bevel_plate(name, sx, sy, sz, cut=0.06, at=(0, 0, 0), mat=None):
    """A chamfered slab — the platform/armour building block."""
    bm = new_bmesh()
    bmesh.ops.create_cube(bm, size=1.0)
    bmesh.ops.scale(bm, vec=Vector((sx, sy, sz)), verts=bm.verts)
    bmesh.ops.bevel(
        bm,
        geom=list(bm.verts) + list(bm.edges) + list(bm.faces),
        offset=cut,
        segments=1,
        affect="EDGES",
    )
    bmesh.ops.translate(bm, vec=Vector(at), verts=bm.verts)
    obj = from_bmesh(bm, name)
    flat_shade(obj)
    if mat:
        assign(obj, mat)
    return obj


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


def triangle_count(obj: bpy.types.Object) -> int:
    total = 0
    for poly in obj.data.polygons:
        total += max(0, len(poly.vertices) - 2)
    return total


def export_glb(obj: bpy.types.Object, out_path: str) -> dict:
    """Exports one object as GLB and returns its manifest record."""
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    recalc_normals(obj)
    apply_transforms(obj)

    for o in bpy.context.scene.objects:
        o.select_set(False)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    bpy.ops.export_scene.gltf(
        filepath=out_path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_normals=True,
        export_materials="EXPORT",
        export_cameras=False,
        export_lights=False,
    )

    tris = triangle_count(obj)
    return {
        "name": obj.name,
        "glb": out_path.replace("\\", "/"),
        "triangles": tris,
        "materials": len([m for m in obj.data.materials if m is not None]),
        "bytes": os.path.getsize(out_path) if os.path.exists(out_path) else 0,
    }


def write_manifest(records: list[dict], path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(records, fh, indent=2)
