"""Renders docs/asset_manifest.md from art/blender/asset_index.json.

Plain CPython — no Blender needed:

    python art/blender/write_manifest_md.py
"""

from __future__ import annotations

import json
import os
from collections import defaultdict

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
INDEX = os.path.join(REPO, "art", "blender", "asset_index.json")
OUT = os.path.join(REPO, "docs", "asset_manifest.md")

BUDGETS = {
    "swarm": 500, "debris": 300, "prop": 2500,
    "interactive": 5000, "machine": 10000, "boss": 20000,
}

GROUP_TITLES = {
    "core": "Kanban Core",
    "metal": "Collectible metal",
    "platforms": "Platform kit",
    "obstacles": "Obstacles",
}


def main() -> None:
    with open(INDEX, encoding="utf-8") as fh:
        records = json.load(fh)

    groups: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        groups[r["glb"].split("/")[2]].append(r)

    total_tris = sum(r["triangles"] for r in records)
    total_bytes = sum(r["bytes"] for r in records)
    over = [r for r in records if r.get("over_budget")]

    lines = [
        "# Asset Manifest",
        "",
        "Generated — **do not edit by hand**. Regenerate with:",
        "",
        "```sh",
        'blender --background --python art/blender/build_assets.py',
        "python art/blender/write_manifest_md.py",
        "```",
        "",
        f"**{len(records)} assets · {total_tris:,} triangles · "
        f"{total_bytes / 1024:.0f} KB total**",
        "",
        f"Budget violations: **{len(over)}**"
        + ("" if not over else " — " + ", ".join(r["glb"] for r in over)),
        "",
        "Every asset is generated by script; there are no hand-authored .blend",
        "files. The generator for each group is a function in",
        "`art/blender/build_assets.py` and the shared modelling helpers live in",
        "`art/blender/mr_kit.py`.",
        "",
        "Triangle budgets (from the brief): "
        + ", ".join(f"{k} ≤ {v}" for k, v in BUDGETS.items())
        + ".",
        "",
    ]

    for group in ("core", "metal", "platforms", "obstacles"):
        rows = groups.get(group)
        if not rows:
            continue
        title = GROUP_TITLES.get(group, group)
        sub = sum(r["triangles"] for r in rows)
        lines += [
            f"## {title}",
            "",
            f"{len(rows)} assets, {sub:,} triangles. "
            f"Source: `build_assets.py::build_{group}()`.",
            "",
            "| Asset | GLB path | Tris | Budget | Mats | Collider | Purpose |",
            "|---|---|---:|---|---:|---|---|",
        ]
        for r in sorted(rows, key=lambda x: x["glb"]):
            limit = BUDGETS[r["budget_class"]]
            flag = " ⚠️" if r.get("over_budget") else ""
            lines.append(
                f"| `{r['name']}` | `{r['glb']}` | {r['triangles']}{flag} | "
                f"{r['budget_class']} (≤{limit}) | {r['materials']} | "
                f"{r['collider']} | {r['purpose']} |"
            )
        lines.append("")

    lines += [
        "## Conventions",
        "",
        "* **Format** — GLB (binary glTF 2.0), one mesh per file.",
        "* **Scale** — metric, 1 unit = 1 metre.",
        "* **Orientation** — exported +Y up (`export_yup=True`).",
        "* **Transforms** — applied; every mesh exports at identity.",
        "* **Normals** — recalculated outward, flat-shaded for the faceted look.",
        "* **Pivots** — at the logical centre of rotation.",
        "* **Materials** — shared, cached instances from `mr_kit.material()`, so",
        "  repeated props reuse one material rather than allocating per asset.",
        "* **Textures** — none. The art direction is flat-shaded colour plus",
        "  emission, which keeps the APK small and avoids texture-compression",
        "  format fragmentation across Android GPUs.",
        "",
        "Swarm pieces are additionally consumed as CPU templates by the batcher",
        "(see `docs/renderer_decision.md`), so their triangle counts are the",
        "single most performance-sensitive numbers in the project.",
        "",
    ]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT} ({len(records)} assets, {total_tris} tris)")


if __name__ == "__main__":
    main()
